# Generated by Django 2.1.1 on 2018-12-01 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_sponsorship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='event',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(related_name='sponsor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sponsorship',
        ),
    ]
