# Generated by Django 2.1.1 on 2018-12-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
    ]
