# Generated by Django 2.1.1 on 2018-12-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrole',
            name='permission',
            field=models.ManyToManyField(to='custom_auth.Permission'),
        ),
    ]
